### ISSUE TITLE
`mpulse.sendBeacon is not a function` method error.

### ISSUE THREAD

**Issue by andersjanmyr** [nicjansma/report-uri-mpulse#1]
Hi, 
I tried out this code and I get the following error. Replacing the `sendBeacon` with `sendMetric` seems to solve the problem, but I don't know if that is the correct function to call.

```
TypeError: mPulse.sendBeacon is not a function at handleReport (/app/index.js:282:12) at Object.<anonymous> (/app/index.js:65:13) at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:111:30) at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:100:5) at handler (/app/node_modules/fastify/lib/handleRequest.js:69:5) at done (/app/node_modules/fastify/lib/contentTypeParser.js:115:7) at Parser.parseJsonContent [as fn] (/app/index.js:291:9) at IncomingMessage.onEnd (/app/node_modules/fastify/lib/contentTypeParser.js:185:25) at IncomingMessage.emit (events.js:215:7) at endReadableNT (_stream_readable.js:1183:12)
```

**Comment by nicjansma** [comment]
Hi @andersjanmyr !  Sorry about that, published an update to `package.json` that points to the latest version of mpulse.js, which has the `.sendBeacon()` function externally exported.

The latest version of the `index.js` also passes-along the User-Agent and Client IP so those are reported correctly in the dashboards.

Let me know if you have any other issues.
